### ISSUE TITLE
range panics if not used in an assign expression

### ISSUE THREAD

**Issue by carnott-snap** [containous/yaegi#258]
The following program `sample.go` triggers a panic:

```go
package main

func main() {
        for range []struct{}{} {
        }
}       
```

Expected result:
```console
$ go run ./sample.go

```

Got:
```console
$ yaegi ./sample.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x618640]

goroutine 1 [running]:
github.com/containous/yaegi/interp.(*Interpreter).cfg.func1(0xc0000daf00, 0xc000185d68)
        /home/user/go/pkg/mod/github.com/containous/yaegi@v0.0.1/interp/cfg.go:70 +0x1220
github.com/containous/yaegi/interp.(*node).Walk(0xc0000daf00, 0xc000185d68, 0xc000185da0)
        /home/user/go/pkg/mod/github.com/containous/yaegi@v0.0.1/interp/interp.go:106 +0xc9
github.com/containous/yaegi/interp.(*node).Walk(0xc0000dab00, 0xc000185d68, 0xc000185da0)
        /home/user/go/pkg/mod/github.com/containous/yaegi@v0.0.1/interp/interp.go:110 +0x70
github.com/containous/yaegi/interp.(*node).Walk(0xc0000daa00, 0xc000185d68, 0xc000185da0)
        /home/user/go/pkg/mod/github.com/containous/yaegi@v0.0.1/interp/interp.go:110 +0x70
github.com/containous/yaegi/interp.(*node).Walk(0xc0000da900, 0xc000185d68, 0xc000185da0)
        /home/user/go/pkg/mod/github.com/containous/yaegi@v0.0.1/interp/interp.go:110 +0x70
github.com/containous/yaegi/interp.(*node).Walk(0xc0000da400, 0xc000185d68, 0xc000185da0)
        /home/user/go/pkg/mod/github.com/containous/yaegi@v0.0.1/interp/interp.go:110 +0x70
github.com/containous/yaegi/interp.(*node).Walk(0xc0000da200, 0xc000185d68, 0xc000185da0)
        /home/user/go/pkg/mod/github.com/containous/yaegi@v0.0.1/interp/interp.go:110 +0x70
github.com/containous/yaegi/interp.(*Interpreter).cfg(0xc0000aa540, 0xc0000da200, 0xc0000a4650, 0x4, 0x0, 0x0, 0x4)
        /home/user/go/pkg/mod/github.com/containous/yaegi@v0.0.1/interp/cfg.go:39 +0x1b2
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc0000aa540, 0xc0000c00c0, 0x39, 0x239, 0xc0000c00c0, 0x39, 0x0, 0xc2f260)
        /home/user/go/pkg/mod/github.com/containous/yaegi@v0.0.1/interp/interp.go:257 +0x135
main.main()
        /home/user/go/pkg/mod/github.com/containous/yaegi@v0.0.1/cmd/yaegi/yaegi.go:77 +0x2e3
```

**Comment by mvertes** [comment]
The problem here is not that the array is empty, it's that `range` is used directly, not in an assign expression. This is not implemented yet. The slightly modified example works correctly:

```go
package main

func main() {
    for _ = range []struct{}{} {
    }
}
```

I'm working on a correction to support the pattern `for range <array|map> { ... }`. Thanks again for the report.
