### ISSUE TITLE
Entering 1=1 triggers a panic

### ISSUE THREAD

**Issue by maxhawkins** [containous/yaegi#280]
OS: macOS 10.14.4
Commit: 2dfede3b90b40723cb2c015adb2f2ab5227825cd

Using the repl:

```sh
~> yaegi
> 1=1    
1:28: panic
panic: reflect: reflect.Value.Set using unaddressable value [recovered]
	panic: reflect: reflect.Value.Set using unaddressable value

goroutine 1 [running]:
github.com/containous/yaegi/interp.runCfg.func1(0xc00018a050, 0xc000112a00)
	/Users/max/go/src/github.com/containous/yaegi/interp/run.go:107 +0x1e9
panic(0x17fc540, 0xc000180250)
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/panic.go:522 +0x1b5
reflect.flag.mustBeAssignable(0x82)
	/usr/local/Cellar/go/1.12.1/libexec/src/reflect/value.go:234 +0x13a
reflect.Value.Set(0x17fb400, 0xc0000ee650, 0x82, 0x17fb400, 0xc0000ee660, 0x82)
	/usr/local/Cellar/go/1.12.1/libexec/src/reflect/value.go:1467 +0x2f
github.com/containous/yaegi/interp.assign.func3(0xc00018a050, 0x1945db0)
	/Users/max/go/src/github.com/containous/yaegi/interp/run.go:256 +0xb6
github.com/containous/yaegi/interp.runCfg(0xc000112a00, 0xc00018a050)
	/Users/max/go/src/github.com/containous/yaegi/interp/run.go:112 +0x70
github.com/containous/yaegi/interp.(*Interpreter).run(0xc0000ce180, 0xc000112900, 0x0)
	/Users/max/go/src/github.com/containous/yaegi/interp/run.go:93 +0x126
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc0000ce180, 0xc0000ee5f0, 0x6, 0xc0001c9df0, 0x5, 0x19136b5, 0x1, 0xc0000ee5f0)
	/Users/max/go/src/github.com/containous/yaegi/interp/interp.go:277 +0x2f9
github.com/containous/yaegi/interp.(*Interpreter).Repl(0xc0000ce180, 0xc000010010, 0xc0000d0000)
	/Users/max/go/src/github.com/containous/yaegi/interp/interp.go:320 +0x1c3
main.main()
	/Users/max/go/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:85 +0x4e2
```

**Comment by bogen85** [comment]
I you write your own REPL (using the existing one as an example), you wrap the eval and recover from the panic.
something like:
```go
func trapEval(i *interp.Interpreter, src string) (reflect.Value, error) {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println("trapEval: ", err)
		}
	}()
	return i.Eval(src)
}
```
using trapEval rather than Eval.

**Comment by mvertes** [comment]
This is a great idea @bogen85. Would you mind to submit a pull request implementing this  ? :smile:

**Comment by bogen85** [comment]
@mvertes Sure! I'll check that is a REPL before using that one, because running scripts one would not want the panic to be trapped (which would cause the script to continue running past errors).

**Comment by bogen85** [comment]
@mvertes  I submitted the PR.
https://github.com/containous/yaegi/pull/297

**Comment by bogen85** [comment]
With an unpatched yaegi, recover is not handled correctly.
```
> import "fmt"
0xc000020180
> func foo() { 1 = 1 }
0xc0000202e0
> func boo() { defer func() { if err := recover(); err != nil { fmt.Println("boo", err)}}(); foo()}
0xc0000205c0
> func boo1() { defer func() { if err := recover(); err != nil { fmt.Println("boo", err)}}(); boo()}
0xc000020b60
> func boo2() { defer func() { if err := recover(); err != nil { fmt.Println("boo", err)}}(); boo1()}
0xc0000210f0
> func boo3() { defer func() { if err := recover(); err != nil { fmt.Println("boo", err)}}(); boo2()}
0xc000021680
> func boo4() { boo3()}
0xc000021b10
> boo4()
1:27: panic
1:52: panic
1:53: panic
1:53: panic
1:53: panic
1:28: panic
1:28: panic
panic: reflect: reflect.Value.Set using unaddressable value [recovered]
	panic: reflect: reflect.Value.Set using unaddressable value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value

goroutine 1 [running]:
github.com/containous/yaegi/interp.runCfg.func1(0xc000180050, 0xc0001ff100)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:107 +0x1e9
panic(0xc39a00, 0xc00000fdc0)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
github.com/containous/yaegi/interp.runCfg.func1(0xc000180460, 0xc0001fe600)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:107 +0x1e9
panic(0xc39a00, 0xc00000fdc0)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
github.com/containous/yaegi/interp.runCfg.func1(0xc000180730, 0xc0001fcd00)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:107 +0x1e9
panic(0xc39a00, 0xc00000fdc0)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
reflect.Value.IsNil(...)
	/usr/lib/go/src/reflect/value.go:1049
github.com/containous/yaegi/interp.isNotNil.func1(0xc000180730, 0xc00000f6c0)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:2188 +0x145
github.com/containous/yaegi/interp.runCfg(0xc0001fcd00, 0xc000180730)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:112 +0x70
github.com/containous/yaegi/interp.genFunctionWrapper.func1.1(0x14b19a0, 0x0, 0x0, 0x14b19a0, 0xc80a60, 0xc0001bd1c0)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:470 +0x357
reflect.callReflect(0xc0001e95c0, 0xc0001bd238, 0xc0001bd220)
	/usr/lib/go/src/reflect/value.go:536 +0x326
reflect.makeFuncStub(0x0, 0x0, 0xc000200000, 0xc000200028, 0xc0001bd478, 0x49c7a1, 0xc0001e9530, 0xc0001e95c0, 0x14b19a0, 0x0, ...)
	/usr/lib/go/src/reflect/asm_amd64.s:20 +0x42
reflect.Value.call(0xbf4cc0, 0xc0001e95c0, 0x13, 0xd14de2, 0x4, 0xc00000fa40, 0x0, 0x0, 0xc0001bd400, 0xc0001bd538, ...)
	/usr/lib/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0xbf4cc0, 0xc0001e95c0, 0x13, 0xc00000fa40, 0x0, 0x0, 0x0, 0xc0001bd620, 0xc0001bd590)
	/usr/lib/go/src/reflect/value.go:308 +0xa4
github.com/containous/yaegi/interp.runCfg.func1(0xc0001804b0, 0xc0001fc200)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:103 +0xf4
panic(0xc39a00, 0xc00000fd40)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
github.com/containous/yaegi/interp.runCfg.func1(0xc0001806e0, 0xc0001f8900)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:107 +0x1e9
panic(0xc39a00, 0xc00000fd40)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
reflect.Value.IsNil(...)
	/usr/lib/go/src/reflect/value.go:1049
github.com/containous/yaegi/interp.isNotNil.func1(0xc0001806e0, 0xc00000f260)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:2188 +0x145
github.com/containous/yaegi/interp.runCfg(0xc0001f8900, 0xc0001806e0)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:112 +0x70
github.com/containous/yaegi/interp.genFunctionWrapper.func1.1(0x14b19a0, 0x0, 0x0, 0x14b19a0, 0xc80a60, 0xc0001bda88)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:470 +0x357
reflect.callReflect(0xc0001e9650, 0xc0001bdb00, 0xc0001bdae8)
	/usr/lib/go/src/reflect/value.go:536 +0x326
reflect.makeFuncStub(0x0, 0x0, 0xc000200000, 0xc000200028, 0xc0001bdd40, 0x49c7a1, 0xc0001e9530, 0xc0001e9650, 0x14b19a0, 0x0, ...)
	/usr/lib/go/src/reflect/asm_amd64.s:20 +0x42
reflect.Value.call(0xbf4cc0, 0xc0001e9650, 0x13, 0xd14de2, 0x4, 0xc00000fb00, 0x0, 0x0, 0xc0001bdd00, 0xc0001bde00, ...)
	/usr/lib/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0xbf4cc0, 0xc0001e9650, 0x13, 0xc00000fb00, 0x0, 0x0, 0x0, 0xc0001bdee8, 0xc0001bde58)
	/usr/lib/go/src/reflect/value.go:308 +0xa4
github.com/containous/yaegi/interp.runCfg.func1(0xc000180500, 0xc0001f3e00)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:103 +0xf4
panic(0xc39a00, 0xc00000fcc0)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
github.com/containous/yaegi/interp.runCfg.func1(0xc000180690, 0xc0001f2600)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:107 +0x1e9
panic(0xc39a00, 0xc00000fcc0)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
reflect.Value.IsNil(...)
	/usr/lib/go/src/reflect/value.go:1049
github.com/containous/yaegi/interp.isNotNil.func1(0xc000180690, 0xc00000ee00)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:2188 +0x145
github.com/containous/yaegi/interp.runCfg(0xc0001f2600, 0xc000180690)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:112 +0x70
github.com/containous/yaegi/interp.genFunctionWrapper.func1.1(0x14b19a0, 0x0, 0x0, 0x14b19a0, 0xc80a60, 0xc0001be350)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:470 +0x357
reflect.callReflect(0xc0001e96e0, 0xc0001be3c8, 0xc0001be3b0)
	/usr/lib/go/src/reflect/value.go:536 +0x326
reflect.makeFuncStub(0x0, 0x0, 0xc000200000, 0xc000200028, 0xc0001be608, 0x49c7a1, 0xc0001e9530, 0xc0001e96e0, 0x14b19a0, 0x0, ...)
	/usr/lib/go/src/reflect/asm_amd64.s:20 +0x42
reflect.Value.call(0xbf4cc0, 0xc0001e96e0, 0x13, 0xd14de2, 0x4, 0xc00000fb40, 0x0, 0x0, 0xc0001be600, 0xc0001be6c8, ...)
	/usr/lib/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0xbf4cc0, 0xc0001e96e0, 0x13, 0xc00000fb40, 0x0, 0x0, 0x0, 0xc0001be7b0, 0xc0001be720)
	/usr/lib/go/src/reflect/value.go:308 +0xa4
github.com/containous/yaegi/interp.runCfg.func1(0xc000180550, 0xc0001ebb00)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:103 +0xf4
panic(0xc39a00, 0xc00000fc40)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
github.com/containous/yaegi/interp.runCfg.func1(0xc000180640, 0xc0001ea300)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:107 +0x1e9
panic(0xc39a00, 0xc00000fc40)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
reflect.Value.IsNil(...)
	/usr/lib/go/src/reflect/value.go:1049
github.com/containous/yaegi/interp.isNotNil.func1(0xc000180640, 0xc00000e9a0)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:2188 +0x145
github.com/containous/yaegi/interp.runCfg(0xc0001ea300, 0xc000180640)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:112 +0x70
github.com/containous/yaegi/interp.genFunctionWrapper.func1.1(0x14b19a0, 0x0, 0x0, 0x14b19a0, 0x0, 0x10)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:470 +0x357
reflect.callReflect(0xc0001e9770, 0xc0001bec90, 0xc0001bec78)
	/usr/lib/go/src/reflect/value.go:536 +0x326
reflect.makeFuncStub(0x0, 0x0, 0xc000200000, 0xc000200028, 0xc0001beed0, 0x49c7a1, 0xc0001e9530, 0xc0001e9770, 0x14b19a0, 0x0, ...)
	/usr/lib/go/src/reflect/asm_amd64.s:20 +0x42
reflect.Value.call(0xbf4cc0, 0xc0001e9770, 0x13, 0xd14de2, 0x4, 0xc00000fb80, 0x0, 0x0, 0xc0001bef00, 0xc0001bef90, ...)
	/usr/lib/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0xbf4cc0, 0xc0001e9770, 0x13, 0xc00000fb80, 0x0, 0x0, 0x0, 0xc0001bf078, 0xc0001befe8)
	/usr/lib/go/src/reflect/value.go:308 +0xa4
github.com/containous/yaegi/interp.runCfg.func1(0xc0001805a0, 0xc0001e7800)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:103 +0xf4
panic(0xbfd960, 0xc000021e70)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
github.com/containous/yaegi/interp.runCfg.func1(0xc0001805f0, 0xc0001e6d00)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:107 +0x1e9
panic(0xbfd960, 0xc000021e70)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
reflect.flag.mustBeAssignable(0x82)
	/usr/lib/go/src/reflect/value.go:234 +0x13a
reflect.Value.Set(0xbfc860, 0xc000024208, 0x82, 0xbfc860, 0xc000024218, 0x82)
	/usr/lib/go/src/reflect/value.go:1467 +0x2f
github.com/containous/yaegi/interp.assign.func3(0xc0001805f0, 0xd470d0)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:258 +0xb6
github.com/containous/yaegi/interp.runCfg(0xc0001e6d00, 0xc0001805f0)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:112 +0x70
github.com/containous/yaegi/interp.call.func4(0xc0001805a0, 0xc0001ec000)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:719 +0xa7f
github.com/containous/yaegi/interp.runCfg(0xc0001e7800, 0xc0001805a0)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:112 +0x70
github.com/containous/yaegi/interp.call.func4(0xc000180550, 0xc0001ec070)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:719 +0xa7f
github.com/containous/yaegi/interp.runCfg(0xc0001ebb00, 0xc000180550)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:112 +0x70
github.com/containous/yaegi/interp.call.func4(0xc000180500, 0xc0001ec0e0)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:719 +0xa7f
github.com/containous/yaegi/interp.runCfg(0xc0001f3e00, 0xc000180500)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:112 +0x70
github.com/containous/yaegi/interp.call.func4(0xc0001804b0, 0xc0001ec150)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:719 +0xa7f
github.com/containous/yaegi/interp.runCfg(0xc0001fc200, 0xc0001804b0)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:112 +0x70
github.com/containous/yaegi/interp.call.func4(0xc000180460, 0xd470d0)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:719 +0xa7f
github.com/containous/yaegi/interp.runCfg(0xc0001fe600, 0xc000180460)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:112 +0x70
github.com/containous/yaegi/interp.call.func4(0xc000180050, 0xd470d0)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:719 +0xa7f
github.com/containous/yaegi/interp.runCfg(0xc0001ff100, 0xc000180050)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:112 +0x70
github.com/containous/yaegi/interp.(*Interpreter).run(0xc00009c1e0, 0xc0001fef00, 0x0)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:93 +0x126
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc00009c1e0, 0xc000024520, 0x7, 0xc0001bfdf0, 0x6, 0xd14395, 0x1, 0xc000024520)
	/home/dwight/go/src/github.com/containous/yaegi/interp/interp.go:277 +0x2f9
github.com/containous/yaegi/interp.(*Interpreter).Repl(0xc00009c1e0, 0xc0000d4000, 0xc0000d4008)
	/home/dwight/go/src/github.com/containous/yaegi/interp/interp.go:320 +0x1c3
main.main()
	/home/dwight/go/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:85 +0x4e2
exit status 2
```

**Comment by bogen85** [comment]
Alright, with regular compiled go, the above is not valid:

**test1.go**
```go
package main
import "fmt"
func foo() { 1 = 1 }
func boo() { defer func() { if err := recover(); err != nil { fmt.Println("boo", err)}}(); foo()}
func boo1() { defer func() { if err := recover(); err != nil { fmt.Println("boo", err)}}(); boo()}
func boo2() { defer func() { if err := recover(); err != nil { fmt.Println("boo", err)}}(); boo1()}
func boo3() { defer func() { if err := recover(); err != nil { fmt.Println("boo", err)}}(); boo2()}
func boo4() { boo3()}

func main() {
	fmt.Println("Hello there!")
	boo4()
	fmt.Println("Good bye!")
}
```

```
$ go run test1.go
# command-line-arguments
./test1.go:3:16: cannot assign to 1
```

However, if we just change it to a panic:
**test2.go**
```go
package main
import "fmt"
func foo() { panic("I'm scared!!!") }
func boo() { defer func() { if err := recover(); err != nil { fmt.Println("boo", err)}}(); foo()}
func boo1() { defer func() { if err := recover(); err != nil { fmt.Println("boo", err)}}(); boo()}
func boo2() { defer func() { if err := recover(); err != nil { fmt.Println("boo", err)}}(); boo1()}
func boo3() { defer func() { if err := recover(); err != nil { fmt.Println("boo", err)}}(); boo2()}
func boo4() { boo3()}

func main() {
	fmt.Println("Hello there!")
	boo4()
	fmt.Println("Good bye!")
}
```

The results are different:
```
$ go run test2.go
Hello there!
boo I'm scared!!!
Good bye!
```

But **yaegi** gives different results on that:
```
$ go run github.com/containous/yaegi/cmd/yaegi < test2.go
0xc000172140
0xc000172210
0xc000172380
0xc0001726a0
0xc000172c40
0xc0001731d0
0xc000173760
0xc000173bf0
Hello there!
1:27: panic
1:52: panic
1:53: panic
1:53: panic
1:53: panic
1:28: panic
2:2: panic
panic: I'm scared!!! [recovered]
	panic: I'm scared!!! [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value

goroutine 1 [running]:
github.com/containous/yaegi/interp.runCfg.func1(0xc0001845f0, 0xc00020dd00)
	/home/dwight/go/src/github.com/containous/yaegi/interp/run.go:107 +0x1e9
panic(0xc39a00, 0xc000218880)
...
```

So, I see this as twofold
1. **yaegi** accepted the 1 = 1
2. **yaegi** did not handle recover correctly, some other panic surfaced

Putting in a recover on the top level as I suggested earlier does not address either of those issues. I would venture that if 1 and 2 above were resolved, this would not be an issue.

Both are different bugs in my opinion.
1. **yaegi** accepted invalid code in a function (the "1 = 1"), and allowed the function to be called
2. **yaegi** is not recovering from panics correcting, even when explicitly recovered.

**Comment by bogen85** [comment]
All the above is in contrast with something like this:
```
$ python
Python 3.7.3 (default, Jun 24 2019, 04:54:02) 
[GCC 9.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def hello(): print("hello")
... 
>>> hello()
hello
>>> def boo(): 1=1
... 
  File "<stdin>", line 1
SyntaxError: can't assign to literal
>>> 
```
Which is almost identical as to how the go compiler handled it as I already mentioned before.
```
$ go run test1.go
# command-line-arguments
./test1.go:3:16: cannot assign to 1
```

**Comment by mpl** [comment]
I believe this is now fixed, as yaegi prints out the panic, but recovers from it and returns the prompt to the user:

```
> 1 = 1
1:28: panic
reflect: reflect.flag.mustBeAssignable using unaddressable value
goroutine 8 [running]:
runtime/debug.Stack(0x1, 0xc00016a400, 0x40)
	/Users/mpl/go1/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/yaegi/interp.(*Interpreter).eval.func1(0xc000175f78)
	/Users/mpl/src/github.com/containous/yaegi/interp/interp.go:362 +0xbc
panic(0x192c200, 0xc0001984d0)
	/Users/mpl/go1/src/runtime/panic.go:967 +0x15d
github.com/containous/yaegi/interp.runCfg.func1(0xc000374000, 0xc000140b00)
	/Users/mpl/src/github.com/containous/yaegi/interp/run.go:123 +0x20c
panic(0x192c200, 0xc0001984d0)
	/Users/mpl/go1/src/runtime/panic.go:967 +0x15d
reflect.flag.mustBeAssignableSlow(0x82)
	/Users/mpl/go1/src/reflect/value.go:247 +0x138
reflect.flag.mustBeAssignable(...)
	/Users/mpl/go1/src/reflect/value.go:234
reflect.Value.Set(0x192b440, 0xc0000389f8, 0x82, 0x192b440, 0xc0000389c8, 0x82)
	/Users/mpl/go1/src/reflect/value.go:1526 +0x3b
github.com/containous/yaegi/interp.assign.func4(0xc000374000, 0x0)
	/Users/mpl/src/github.com/containous/yaegi/interp/run.go:448 +0xb6
github.com/containous/yaegi/interp.runCfg(0xc000140b00, 0xc000374000)
	/Users/mpl/src/github.com/containous/yaegi/interp/run.go:129 +0x6d
github.com/containous/yaegi/interp.(*Interpreter).run(0xc0000c21a0, 0xc000140a00, 0x0)
	/Users/mpl/src/github.com/containous/yaegi/interp/run.go:107 +0x296
github.com/containous/yaegi/interp.(*Interpreter).eval(0xc0000c21a0, 0xc000038908, 0x6, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/mpl/src/github.com/containous/yaegi/interp/interp.go:444 +0x632
github.com/containous/yaegi/interp.(*Interpreter).Eval(...)
	/Users/mpl/src/github.com/containous/yaegi/interp/interp.go:335
github.com/containous/yaegi/interp.(*Interpreter).EvalWithContext.func1(0xc000042300, 0xc0000c21a0, 0xc000038908, 0x6, 0xc00000ede0, 0xc000198290)
	/Users/mpl/src/github.com/containous/yaegi/interp/interp.go:483 +0x84
created by github.com/containous/yaegi/interp.(*Interpreter).EvalWithContext
	/Users/mpl/src/github.com/containous/yaegi/interp/interp.go:481 +0x14d

> foo := 1
: 1
> 
> 
> println(foo)
1
> 
```
