### ISSUE TITLE
Panic when attempting to return interface

### ISSUE THREAD

**Issue by floren** [containous/yaegi#281]
The following Go program declares a type which fulfills the io.Reader interface, then in the main function instantiates the type and calls Read to test it. It runs fine:

```go
package main

import (
	"io"
	"fmt"
)

type X struct {
}

func (x *X) Read(p []byte) (n int, err error) {
	fmt.Println("Read called!")
	return
}

func NewX() io.Reader {
	return &X{}
}

func main() {
	x := NewX()
	b := make([]byte, 128)
	x.Read(b)
}
```

This program attempts to use the same io.Reader implementation defined in a yaegi script. It crashes:

```go
package main

import (
	"io"
	"log"
	"reflect"

	"github.com/containous/yaegi/interp"
	"github.com/containous/yaegi/stdlib"
)

var script = `
import (
	"io"
	"fmt"
)

type X struct {
}

func (x *X) Read(p []byte) (n int, err error) {
	fmt.Println("Read called!")
	return
}

func NewX() io.Reader {
	return &X{}
}`

func main() {
	vm := interp.New(interp.Options{})
	vm.Use(stdlib.Symbols)

	_, err := vm.Eval(script)
	if err != nil {
		log.Fatal(err)
	}

	var v reflect.Value
	v, err = vm.Eval("NewX")
	if err != nil {
		log.Fatal(err)
	}
	n, ok := v.Interface().(func() io.Reader)
	if !ok {
		log.Fatal("couldn't get new func")
	}

	x := n()

	b := make([]byte, 128)
	x.Read(b)
}
```
The panic is as follows:

```
16:10: panic
panic: reflect.Set: value of type *struct {} is not assignable to type io.Reader [recovered]
	panic: reflect.Set: value of type *struct {} is not assignable to type io.Reader

goroutine 1 [running]:
github.com/containous/yaegi/interp.runCfg.func1(0xc0000c9810, 0xc0001b9800)
	/home/john/go/pkg/mod/github.com/containous/yaegi@v0.0.3/interp/run.go:107 +0x1e9
panic(0xbfc9e0, 0xc000154b00)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
reflect.Value.assignTo(0xbead00, 0xc0000c2800, 0x196, 0xd1d7d8, 0xb, 0xc51e00, 0xc000154ae0, 0x5c47fa, 0xbead00, 0xc0000c2800)
	/usr/local/go/src/reflect/value.go:2339 +0x437
reflect.Value.Set(0xc51e00, 0xc000154ae0, 0x194, 0xbead00, 0xc0000c2800, 0x196)
	/usr/local/go/src/reflect/value.go:1473 +0xa8
github.com/containous/yaegi/interp._return.func3(0xc0000c9810, 0xc0000b7580)
	/home/john/go/pkg/mod/github.com/containous/yaegi@v0.0.3/interp/run.go:1270 +0x88
github.com/containous/yaegi/interp.runCfg(0xc0001b9800, 0xc0000c9810)
	/home/john/go/pkg/mod/github.com/containous/yaegi@v0.0.3/interp/run.go:112 +0x70
github.com/containous/yaegi/interp.genFunctionWrapper.func1.1(0x14b09a0, 0x0, 0x0, 0x14b09a0, 0x0, 0xc0000b7780)
	/home/john/go/pkg/mod/github.com/containous/yaegi@v0.0.3/interp/run.go:468 +0x357
reflect.callReflect(0xc0001aa870, 0xc000191f00, 0xc000191ee8)
	/usr/local/go/src/reflect/value.go:536 +0x326
reflect.makeFuncStub(0xbf8f60, 0xc0001aa870, 0x13, 0xbf8f01, 0xbf8f60, 0xc0001aa870, 0x0, 0x0, 0xc2e260, 0x13, ...)
	/usr/local/go/src/reflect/asm_amd64.s:20 +0x42
main.main()
	/tmp/yg/yaegi.go:49 +0x19e
exit status 2
```

Am I doing something outside the scope of what Yaegi should allow, or is this a bug?

**Comment by traetox** [comment]
I am no longer seeing this panic using the following versions:
go1.13.15 linux/amd64
github.com/containous/yaegi v0.8.13

Has this been addressed/fixed?

**Comment by mvertes** [comment]
Yes, this issue has been most probably addressed since (but I do not recall exactly). It can be safely closed.

Thanks for the notice.
