### ISSUE TITLE
Panic when evaluating package before use

### ISSUE THREAD

**Issue by fhs** [containous/yaegi#290]
```
$ rlwrap yaegi
> import "fmt"
0xc000020140
> fmt
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/containous/yaegi/interp.valueGenerator.func1(0xc000154050, 0xc0000242a0, 0x0, 0x4)
	/home/fhs/go/pkg/mod/github.com/containous/yaegi@v0.0.4-0.20190726060203-f1995200485a/interp/value.go:10 +0x4e
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc00006e120, 0xc00002422c, 0x4, 0xc000191df0, 0x3, 0xd14415, 0x1, 0xc00002422c)
	/home/fhs/go/pkg/mod/github.com/containous/yaegi@v0.0.4-0.20190726060203-f1995200485a/interp/interp.go:283 +0x36a
github.com/containous/yaegi/interp.(*Interpreter).Repl(0xc00006e120, 0xc0000a8000, 0xc0000a8008)
	/home/fhs/go/pkg/mod/github.com/containous/yaegi@v0.0.4-0.20190726060203-f1995200485a/interp/interp.go:320 +0x1c3
main.main()
	/home/fhs/go/pkg/mod/github.com/containous/yaegi@v0.0.4-0.20190726060203-f1995200485a/cmd/yaegi/yaegi.go:85 +0x4e2
```

After referencing something within the package, the package evalutes to `<nil>`. I expect it to evaluate to `<nil>` even before something is referenced in it.
```
$ rlwrap yaegi
> import "fmt"
0xc00012a0f0
> fmt.Printf
0x4f09b0
> fmt
<nil>
> 
```

yaegi version:
```
$ goversion -m $(which yaegi)
/home/fhs/go/bin/yaegi go1.12.7
	path  github.com/containous/yaegi/cmd/yaegi
	mod   github.com/containous/yaegi            v0.0.4-0.20190726060203-f1995200485a
```

**Comment by mpl** [comment]
This seems to be fixed now:

```
% yaegi
> import "fmt"
: 0xc000196470
> fmt
> 
> 
> fmt.Println
: 0x11130c0
> fmt
: <nil>
> 
```

so I think we can close.
