### ISSUE TITLE
alias to interface type

### ISSUE THREAD

**Issue by mvertes** [containous/yaegi#380]
The following program `sample.go` triggers a panic:

```go
package main
  
import "fmt"

type Error interface {
    error
    Code() string
}

type MyError Error

type T struct {
    Name string
}

func (t *T) Error() string { return "err: " + t.Name }
func (t *T) Code() string  { return "code: " + t.Name }

func newT(s string) MyError { return &T{s} }

func main() {
    t := newT("foo")
    fmt.Println(t.Code())
}
```

Expected result:
```console
$ go run ./sample.go
code: foo
```

Got:
```console
$ yaegi ./sample.go
scope.go:153: nil reflect type
panic: nil reflect type

goroutine 1 [running]:
log.Panic(0xc00018d768, 0x1, 0x1)
        /usr/lib/go/src/log/log.go:338 +0xac
github.com/containous/yaegi/interp.(*scope).add(0xc0002501c0, 0xc00023f790, 0xc00024b200)
        /home/marc/go/src/github.com/containous/yaegi/interp/scope.go:153 +0x173
github.com/containous/yaegi/interp.(*Interpreter).cfg.func1(0xc00024a800, 0xc00018dd18)
        /home/marc/go/src/github.com/containous/yaegi/interp/cfg.go:250 +0x2438
github.com/containous/yaegi/interp.(*node).Walk(0xc00024a800, 0xc00018dd18, 0xc00018dd50)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:112 +0xc9
github.com/containous/yaegi/interp.(*node).Walk(0xc0000ec300, 0xc00018dd18, 0xc00018dd50)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:116 +0x70
github.com/containous/yaegi/interp.(*Interpreter).cfg(0xc0000eea00, 0xc0000ec300, 0xc0000c49d8, 0x4, 0x0, 0x0, 0x0)
        /home/marc/go/src/github.com/containous/yaegi/interp/cfg.go:39 +0x1b2
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc0000eea00, 0xc0000e46e0, 0x157, 0x357, 0xc0000e46e0, 0x157, 0x0, 0xc0002241e0)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:266 +0x1ed
main.main()
        /home/marc/go/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:77 +0x2f9
```

**Comment by mvertes** [comment]
This issue is a blocker for #276
