### ISSUE TITLE
interp: array decl assignment causes a panic

### ISSUE THREAD

**Issue by kortschak** [containous/yaegi#394]
The following test case panics.
```
package main

import "fmt"

func main() {
	a := [...]int{1, 2, 3}
	b := a
	b[0] = -1
	fmt.Println(a)
}

// Output:
// [1 2 3]
```

```
~/src/github.com/containous/yaegi [master]$ git rev-parse HEAD
2c2b471cb91f520b10f9ea8e0f988de221c94b6a
~/src/github.com/containous/yaegi [master]$ go run _test/array0.go
[1 2 3]
~/src/github.com/containous/yaegi [master]$ yaegi _test/array0.go
panic: runtime error: slice bounds out of range [1:0] [recovered]
	panic: _test/array0.go:7:2: CFG post-order panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/containous/yaegi/interp.(*Interpreter).cfg.func2.1(0xc000263400)
	/home/user/src/github.com/containous/yaegi/interp/cfg.go:347 +0xba
panic(0xd6f9e0, 0xc00015e080)
	/home/user/go/src/runtime/panic.go:679 +0x1b2
github.com/containous/yaegi/interp.compositeArrayLen(0xc000263600, 0xc000160440)
	/home/user/src/github.com/containous/yaegi/interp/cfg.go:1741 +0x17d
github.com/containous/yaegi/interp.(*Interpreter).cfg.func2(0xc000263400)
	/home/user/src/github.com/containous/yaegi/interp/cfg.go:394 +0x6ecb
github.com/containous/yaegi/interp.(*node).Walk(0xc000263400, 0xc0001a3d18, 0xc0001a3d50)
	/home/user/src/github.com/containous/yaegi/interp/interp.go:119 +0xaf
github.com/containous/yaegi/interp.(*node).Walk(0xc000262a00, 0xc0001a3d18, 0xc0001a3d50)
	/home/user/src/github.com/containous/yaegi/interp/interp.go:116 +0x70
github.com/containous/yaegi/interp.(*node).Walk(0xc000262500, 0xc0001a3d18, 0xc0001a3d50)
	/home/user/src/github.com/containous/yaegi/interp/interp.go:116 +0x70
github.com/containous/yaegi/interp.(*node).Walk(0xc000262000, 0xc0001a3d18, 0xc0001a3d50)
	/home/user/src/github.com/containous/yaegi/interp/interp.go:116 +0x70
github.com/containous/yaegi/interp.(*Interpreter).cfg(0xc00024e000, 0xc000262000, 0xc000154070, 0x4, 0x0, 0x0, 0x0)
	/home/user/src/github.com/containous/yaegi/interp/cfg.go:40 +0x1b2
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc00024e000, 0xc000258000, 0x7e, 0x27e, 0xc000258000, 0x7e, 0x0, 0xc000153d10)
	/home/user/src/github.com/containous/yaegi/interp/interp.go:266 +0x1ed
main.main()
	/home/user/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:77 +0x2f9
```

Also with this
```
package main

import "fmt"

func main() {
        a := [...]int{1, 2, 3}
        b := a
        fmt.Println(b)
}

// Output:
// [1 2 3]
```

Note that the following code does not panic, nor does the failure case for #341 any longer, so that issue can probably be closed.
```
package main

import "fmt"

func main() {
	a := [...]int{1, 2, 3}
	fmt.Println(a)
}

// Output:
// [1 2 3]
```

**Comment by kortschak** [comment]
Additional data point. This code does work.
```
package main

import "fmt"

func main() {
        a := [...]int{1, 2, 3}
        var b [3]int = a
        fmt.Println(b)
}

// Output:
// [1 2 3]
```

And the following, which was the case I was originally actually interested in testing, just spelled a different way.
```
package main

import "fmt"

func main() {
	a := [...]int{1, 2, 3}
	var b [3]int = a
	b[0] = -1
	fmt.Println(a)
}

// Output:
// [1 2 3]
```

**Comment by kortschak** [comment]
The problem appears to be that `interp.cfg` in the `assignStmt` and `defineStmt` cases assumes an array will be defined as a literal and so calls `compositeArrayLen`which calculates the length of the array from the source, but this information does not exist in this case.
