### ISSUE TITLE
interp: zero length arrays are not properly handled

### ISSUE THREAD

**Issue by kortschak** [containous/yaegi#396]
Currently the distinction between slices and arrays is made via the `itype.size` field. This is not correct as the zero value of this field is used to indicate that an arrayish is a slice, otherwise it is an array. This means that if a `[0]T` is given to the intepreter it types it as a `[]T`.

This is demonstrated by the following two examples.

```
import "fmt"

func main() {
	a := [...]byte{}
	fmt.Printf("%T\n", a)
}

// Output:
// [0]uint8
```

```
$ go run _test/a38.go 
[0]uint8
$ yaegi _test/a38.go 
[]uint8
```

The second case is more dramatic.

```
package main

import "fmt"

func main() {
	a := [...]byte{}
	b := a
	fmt.Printf("%T %T\n", a, b)
}

// Output:
// [0]uint8 [0]uint8
```

```
$ go run _test/a39.go 
[0]uint8 [0]uint8
$ yaegi _test/a39.go 
panic: runtime error: slice bounds out of range [1:0] [recovered]
	panic: _test/a39.go:7:2: CFG post-order panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/containous/yaegi/interp.(*Interpreter).cfg.func2.1(0xc000255100)
	/home/user/src/github.com/containous/yaegi/interp/cfg.go:347 +0xba
panic(0xd6f7e0, 0xc00015a0a0)
	/home/user/go/src/runtime/panic.go:679 +0x1b2
github.com/containous/yaegi/interp.compositeArrayLen(0xc000255300, 0xc000158440)
	/home/user/src/github.com/containous/yaegi/interp/cfg.go:1741 +0x17d
github.com/containous/yaegi/interp.(*Interpreter).cfg.func2(0xc000255100)
	/home/user/src/github.com/containous/yaegi/interp/cfg.go:394 +0x6ecb
github.com/containous/yaegi/interp.(*node).Walk(0xc000255100, 0xc000197d18, 0xc000197d50)
	/home/user/src/github.com/containous/yaegi/interp/interp.go:119 +0xaf
github.com/containous/yaegi/interp.(*node).Walk(0xc000254a00, 0xc000197d18, 0xc000197d50)
	/home/user/src/github.com/containous/yaegi/interp/interp.go:116 +0x70
github.com/containous/yaegi/interp.(*node).Walk(0xc000254500, 0xc000197d18, 0xc000197d50)
	/home/user/src/github.com/containous/yaegi/interp/interp.go:116 +0x70
github.com/containous/yaegi/interp.(*node).Walk(0xc000254000, 0xc000197d18, 0xc000197d50)
	/home/user/src/github.com/containous/yaegi/interp/interp.go:116 +0x70
github.com/containous/yaegi/interp.(*Interpreter).cfg(0xc000242000, 0xc000254000, 0xc000150088, 0x4, 0x0, 0x0, 0x0)
	/home/user/src/github.com/containous/yaegi/interp/cfg.go:40 +0x1b2
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc000242000, 0xc00024a000, 0x84, 0x284, 0xc00024a000, 0x84, 0x0, 0xc000145e00)
	/home/user/src/github.com/containous/yaegi/interp/interp.go:266 +0x1ed
main.main()
	/home/user/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:77 +0x2f9
```

I have had some success in fixing this by ising the `sizedef` field to indicate that the type is an array, playing wackamole with places where the 0 assumption has been made. However, I cannot resolve how the following is handled, `var a [4]int; s := a[:]`. I am unable to find where the `[:]` is indentified to enable the `s` node's `sizedef` to be zeroed out. The `s` never shows up in `nodeType` without the node type already set. Any hints would be greatly appreciated.

Note that this failure is distinct from the failure fixed by #395, though changes there are needed to fix this as far as I have got.

**Comment by kortschak** [comment]
I have resolved this issue. It is made somewhat more difficult to spelunk this because of what looks like a very minor issue, but here makes a big impact. The double-negative resulting from the use of the name `incomplete` in the `itype` field. It would make it easier to hold in a head if this gymnastics were not necessary. There are two possible approaches, invert the logic (not a light touch), or probably preferably just renaming it to `more`, which has the same logical orientation, but is not a negation.
