### ISSUE TITLE
assign a var from binary func 

### ISSUE THREAD

**Issue by mvertes** [containous/yaegi#408]
The following program `sample.go` triggers a panic:

```go
package main

import "time"
    
var NowTime func() time.Time
    
func main() {
    NowTime = time.Now
    println("ok")
}   
```

Expected result:
```console
$ go run ./sample.go
ok
```

Got:
```console
$ yaegi ./sample.go
./sample.go:8:12: panic
panic: reflect.Set: value of type func() time.Time is not assignable to type *interp.node [recovered]
        panic: reflect.Set: value of type func() time.Time is not assignable to type *interp.node

goroutine 1 [running]:
github.com/containous/yaegi/interp.runCfg.func1(0xc0000d3540, 0xc0000dbb00)
        /home/marc/go/src/github.com/containous/yaegi/interp/run.go:107 +0x1e0
panic(0xc957a0, 0xc000134610)
        /usr/lib/go/src/runtime/panic.go:679 +0x1b2
reflect.Value.assignTo(0xc921e0, 0xe07408, 0x13, 0xdd3392, 0xb, 0xd59e40, 0x0, 0xfffffff700036301, 0xc00018bcd0, 0x49a2b0)
        /usr/lib/go/src/reflect/value.go:2403 +0x432
reflect.Value.Set(0xd59e40, 0xc0000106d0, 0x196, 0xc921e0, 0xe07408, 0x13)
        /usr/lib/go/src/reflect/value.go:1537 +0xbd
github.com/containous/yaegi/interp.assign.func3(0xc0000d3540, 0xc00000f320)
        /home/marc/go/src/github.com/containous/yaegi/interp/run.go:258 +0xb6
github.com/containous/yaegi/interp.runCfg(0xc0000dbb00, 0xc0000d3540)
        /home/marc/go/src/github.com/containous/yaegi/interp/run.go:112 +0x7a
github.com/containous/yaegi/interp.(*Interpreter).run(0xc0000dca00, 0xc0000db300, 0xc0000d3400)
        /home/marc/go/src/github.com/containous/yaegi/interp/run.go:93 +0x12c
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc0000dca00, 0xc000088070, 0x6e, 0x26e, 0xc000088070, 0x6e, 0x0, 0x1)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:303 +0x3f0
main.main()
        /home/marc/go/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:79 +0x42d
```

**Comment by mvertes** [comment]
Solving this issue is necessary for #276
