### ISSUE TITLE
panic in interface to interface type assertion

### ISSUE THREAD

**Issue by cosmos72** [containous/yaegi#436]
The following program `sample.go` triggers a panic:

```go
package main

import (
	"fmt"
)

type X struct{}

func (X) Foo() int {
	return 1
}
func (X) Bar() int {
	return 2
}

type Foo interface {
	Foo() int
}
type Bar interface {
	Bar() int
}

func main() {
	var x X
	var i Foo = x
	j := i.(Bar)

	fmt.Println(j.Bar())
}
```

Expected result:
```console
$ go run ./sample.go
2
```

Got:
```console
$ yaegi ./sample.go
./sample.go:24:6: panic
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x65dffd]

goroutine 1 [running]:
github.com/containous/yaegi/interp.runCfg.func1(0xc00026c0a0, 0xc00027e500)
	/home/max/go/src/github.com/containous/yaegi/interp/run.go:112 +0x218
panic(0xce6800, 0x15215f0)
	/usr/local/go-1.13.3/src/runtime/panic.go:679 +0x1b2
github.com/containous/yaegi/interp.getMethodByName.func1(0xc00026c0a0, 0xc000278660)
	/home/max/go/src/github.com/containous/yaegi/interp/run.go:1094 +0x14d
github.com/containous/yaegi/interp.runCfg(0xc00027e500, 0xc00026c0a0)
	/home/max/go/src/github.com/containous/yaegi/interp/run.go:118 +0x7a
github.com/containous/yaegi/interp.(*Interpreter).run(0xc000268000, 0xc00027dd00, 0xc00026c000)
	/home/max/go/src/github.com/containous/yaegi/interp/run.go:96 +0x239
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc000268000, 0xc000272000, 0x108, 0x308, 0xc000272000, 0x108, 0x0, 0x1)
	/home/max/go/src/github.com/containous/yaegi/interp/interp.go:360 +0x42d
main.main()
	/home/max/go/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:82 +0x42d
```

**Comment by cosmos72** [comment]
Interestingly, the two-value type assertion works:
```go
func main() {
	var x X
	var i Foo = x
	j, ok := i.(Bar)

	fmt.Println(j.Bar(), ok)
}
```
prints
```console
$ yaegi ./sample.go
2 true
```

**Comment by mvertes** [comment]
Your test is interesting, thanks. It exhibits a problem about dynamic type (the concrete type assigned to an interface variable during runtime) being lost when an interface is set from another interface rather than a concrete type. I'm preparing a fix tor this subtle transitivity issue.
