### ISSUE TITLE
return nil

### ISSUE THREAD

**Issue by mvertes** [containous/yaegi#464]
The following program `sample.go` triggers a panic:

```go
package main        
                
import "fmt"
    
func f() (host, port string, err error) {
    return "", "", nil
}
    
func main() {
    h, p, err := f()
    fmt.Println(h, p, err)
}
```

Expected result:
```console
$ go run ./sample.go
  <nil>
```

Got:
```console
$ yaegi ./sample.go
panic: runtime error: index out of range [2] with length 2 [recovered]
        panic: _test/nil0.go:4:2: CFG post-order panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/containous/yaegi/interp.(*Interpreter).cfg.func2.1(0xc00018b100)
        /home/marc/go/src/github.com/containous/yaegi/interp/cfg.go:366 +0xba
panic(0xd775e0, 0xc000036240)
        /usr/lib/go/src/runtime/panic.go:679 +0x1b2
github.com/containous/yaegi/interp.(*Interpreter).cfg.func2(0xc00018b100)
        /home/marc/go/src/github.com/containous/yaegi/interp/cfg.go:1071 +0xb5db
github.com/containous/yaegi/interp.(*node).Walk(0xc00018b100, 0xc0001bbce8, 0xc0001bbd20)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:171 +0xaf
github.com/containous/yaegi/interp.(*node).Walk(0xc00018b000, 0xc0001bbce8, 0xc0001bbd20)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:168 +0x70
github.com/containous/yaegi/interp.(*node).Walk(0xc00018a300, 0xc0001bbce8, 0xc0001bbd20)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:168 +0x70
github.com/containous/yaegi/interp.(*node).Walk(0xc00018a100, 0xc0001bbce8, 0xc0001bbd20)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:168 +0x70
github.com/containous/yaegi/interp.(*Interpreter).cfg(0xc000260b00, 0xc00018a100, 0xc0000341b0, 0x4, 0x0, 0x0, 0x0)
        /home/marc/go/src/github.com/containous/yaegi/interp/cfg.go:48 +0x1b2
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc000260b00, 0xc000272000, 0x85, 0x285, 0xc000272000, 0x85, 0x0, 0x1)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:322 +0x1ee
main.main()
        /home/marc/go/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:82 +0x42e
```

**Comment by mvertes** [comment]
Note that there is no error if function signature is
```go
func f() (host string, port string, err  error)
```
instead of
```go
func f() (host, port string, err error)
```
