### ISSUE TITLE
composite object init from operator expression

### ISSUE THREAD

**Issue by mvertes** [containous/yaegi#507]
The following program `sample.go` triggers a panic:

```go
package main

import "fmt"
    
type T struct {
    m uint16
}

var t = T{1<<2 | 1<<3}
    
func main() {
    fmt.Println(t)
}
```

Expected result:
```console
$ go run ./sample.go
{12}
```

Got:
```console
$ yaegi ./sample.go
panic: reflect.Value.Convert: value of type struct { Xm uint16 } cannot be converted to type uint16

goroutine 1 [running]:
reflect.Value.Convert(0xc0000ca8a0, 0xc0000c4aa8, 0x199, 0xfc50e0, 0xc9ece0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/reflect/value.go:2415 +0x224
github.com/containous/yaegi/interp.convertLiteralValue(0xc0000ef700, 0xfc50e0, 0xc9ece0)
        /home/marc/go/src/github.com/containous/yaegi/interp/run.go:2279 +0x99
github.com/containous/yaegi/interp.compositeLit(0xc0000ef500)
        /home/marc/go/src/github.com/containous/yaegi/interp/run.go:1607 +0x178
github.com/containous/yaegi/interp.setExec.func1(0xc0000ef500)
        /home/marc/go/src/github.com/containous/yaegi/interp/cfg.go:1829 +0xb2
github.com/containous/yaegi/interp.setExec.func1(0xc0000ef700)
        /home/marc/go/src/github.com/containous/yaegi/interp/cfg.go:1818 +0x25d
github.com/containous/yaegi/interp.setExec.func1(0xc0000efb00)
        /home/marc/go/src/github.com/containous/yaegi/interp/cfg.go:1818 +0x25d
github.com/containous/yaegi/interp.setExec.func1(0xc0000ef800)
        /home/marc/go/src/github.com/containous/yaegi/interp/cfg.go:1818 +0x25d
github.com/containous/yaegi/interp.setExec(0xc0000ef800)
        /home/marc/go/src/github.com/containous/yaegi/interp/cfg.go:1832 +0xf5
github.com/containous/yaegi/interp.genRun.func1(0xc0000ef200, 0xc000197d48)
        /home/marc/go/src/github.com/containous/yaegi/interp/cfg.go:1559 +0x44
github.com/containous/yaegi/interp.(*node).Walk(0xc0000ef200, 0xc000197d48, 0x0)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:164 +0xc9
github.com/containous/yaegi/interp.(*node).Walk(0xc0000ee500, 0xc000197d48, 0x0)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:168 +0x70
github.com/containous/yaegi/interp.genRun(0xc0000ee500, 0xc0002264b0, 0xc0000c49f8)
        /home/marc/go/src/github.com/containous/yaegi/interp/cfg.go:1547 +0x64
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc000238f20, 0xc0000c2280, 0x71, 0x271, 0xc0000c2280, 0x71, 0x0, 0x1)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:353 +0x388
main.main()
        /home/marc/go/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:82 +0x42e
```

**Comment by mvertes** [comment]
Note that the test passes, using a simpler init expression, such as
```go
var t = T{1 << 2}
```
