### ISSUE TITLE
panic: value of type *strings.Reader is not assignable to type io.ReadCloser

### ISSUE THREAD

**Issue by bitfield** [containous/yaegi#558]
The following program `sample.go` triggers a panic:

```go
package main

import (
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"strings"
)

type readAutoCloser struct {
	r io.ReadCloser
}

func (a readAutoCloser) Read(b []byte) (n int, err error) {
	if a.r == nil {
		return 0, io.EOF
	}
	n, err = a.r.Read(b)
	if err == io.EOF {
		a.Close()
	}
	return n, err
}

func (a readAutoCloser) Close() error {
	if a.r == nil {
		return nil
	}
	return a.r.(io.Closer).Close()
}

type pipe struct {
	Reader readAutoCloser
}

func newReadAutoCloser(r io.Reader) readAutoCloser {
	if _, ok := r.(io.Closer); !ok {
		return readAutoCloser{ioutil.NopCloser(r)}
	}
	return readAutoCloser{r.(io.ReadCloser)}
}

func main() {
	p := &pipe{}
	p.Reader = newReadAutoCloser(strings.NewReader("test"))
	b, err := ioutil.ReadAll(p.Reader)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(b)
}
```

Expected result:
```console
$ go run ./sample.go
[116 101 115 116]
```

Got:
```console
main.go:38:17: panic
main.go:45:8: panic
reflect.Set: value of type *strings.Reader is not assignable to type io.ReadCloser
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc0002fe200, 0x40)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/yaegi/interp.(*Interpreter).Eval.func1(0xc00012de10)
        /Users/john/go/pkg/mod/github.com/containous/yaegi@v0.8.0/interp/interp.go:320 +0xbc
panic(0x188f440, 0xc00006fe60)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:967 +0x15d
github.com/containous/yaegi/interp.runCfg.func1(0xc0002ee0a0, 0xc00030cc00)
        /Users/john/go/pkg/mod/github.com/containous/yaegi@v0.8.0/interp/run.go:113 +0x20c
panic(0x188f440, 0xc00006fe60)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:967 +0x15d
github.com/containous/yaegi/interp.runCfg.func1(0xc0002ee140, 0xc00030ad00)
        /Users/john/go/pkg/mod/github.com/containous/yaegi@v0.8.0/interp/run.go:113 +0x20c
panic(0x188f440, 0xc00006fe60)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:967 +0x15d
reflect.Value.assignTo(0x196d880, 0xc00000ff40, 0x16, 0x19c1190, 0xb, 0x18ec220, 0xc00006fe40, 0x19a8c40, 0x196d880, 0xc00000ff40)
        /usr/local/Cellar/go/1.14/libexec/src/reflect/value.go:2403 +0x426
reflect.Value.Set(0x18ec220, 0xc00006fe40, 0x194, 0x196d880, 0xc00000ff40, 0x16)
        /usr/local/Cellar/go/1.14/libexec/src/reflect/value.go:1532 +0xbd
github.com/containous/yaegi/interp.typeAssert.func1(0xc0002ee140, 0xc00000fc80)
        /Users/john/go/pkg/mod/github.com/containous/yaegi@v0.8.0/interp/run.go:162 +0xba
github.com/containous/yaegi/interp.runCfg(0xc00030ad00, 0xc0002ee140)
        /Users/john/go/pkg/mod/github.com/containous/yaegi@v0.8.0/interp/run.go:119 +0x6d
github.com/containous/yaegi/interp.call.func5(0xc0002ee0a0, 0xc0002edea0)
        /Users/john/go/pkg/mod/github.com/containous/yaegi@v0.8.0/interp/run.go:787 +0xb18
github.com/containous/yaegi/interp.runCfg(0xc00030cc00, 0xc0002ee0a0)
        /Users/john/go/pkg/mod/github.com/containous/yaegi@v0.8.0/interp/run.go:119 +0x6d
github.com/containous/yaegi/interp.(*Interpreter).run(0xc000001200, 0xc00030c300, 0xc0002ee000)
        /Users/john/go/pkg/mod/github.com/containous/yaegi@v0.8.0/interp/run.go:97 +0x239
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc000001200, 0xc0002f6000, 0x322, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/john/go/pkg/mod/github.com/containous/yaegi@v0.8.0/interp/interp.go:388 +0x41f
main.main()
        /Users/john/go/pkg/mod/github.com/containous/yaegi@v0.8.0/cmd/yaegi/yaegi.go:94 +0x548
```

**Comment by mvertes** [comment]
I started to analyse this issue. The problem comes from a type assertion which gives a wrong result in yaegi. As a workaround, you could replace `newReadAutoCloser` with the following code, to make the program work:
```go
 func newReadAutoCloser(r io.Reader) readAutoCloser {
    return readAutoCloser{ioutil.NopCloser(r)}
}
```
Of course, I'm working on a real fix. Thanks again for this report.

**Comment by bitfield** [comment]
Thanks @mvertes! Yes, it's no problem for my project; I've made a change along the lines you suggest. If I can be of any help resolving this, just let me know.
