### ISSUE TITLE
assign function using a recursive struct with forward dependency

### ISSUE THREAD

**Issue by mvertes** [containous/yaegi#570]
The following program `sample.go` triggers a panic:

```go
package main
  
type T struct {
    t func(*T)
    y *xxx
}

func f(t *T) { println("in f") }

var x = &T{t: f}

type xxx struct{}

func main() {
    println("ok")
}
```

Expected result:
```console
$ go run ./sample.go
ok
```

Got:
```console
$ yaegi ./sample.go
./sample.go:12:12: panic
reflect.Set: value of type func(*struct { Xt func(*interface {}); Xy *struct {} }) is not assignable to type func(*interface {})
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc0003ae000, 0x40)
        /home/marc/sdk/go1.14.1/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/yaegi/interp.(*Interpreter).Eval.func1(0xc000133e10)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:320 +0xbc
panic(0xc922a0, 0xc0001149d0)
        /home/marc/sdk/go1.14.1/src/runtime/panic.go:967 +0x166
github.com/containous/yaegi/interp.runCfg.func1(0xc000392000, 0xc0003a4c00)
        /home/marc/go/src/github.com/containous/yaegi/interp/run.go:113 +0x20c
panic(0xc922a0, 0xc0001149d0)
        /home/marc/sdk/go1.14.1/src/runtime/panic.go:967 +0x166
reflect.Value.assignTo(0xc00010e8a0, 0xc00039e750, 0x13, 0xdc35a4, 0xb, 0xc00010e4e0, 0x0, 0xc000135800, 0xc00010e8a0, 0x0)
        /home/marc/sdk/go1.14.1/src/reflect/value.go:2403 +0x426
reflect.Value.Set(0xc00010e4e0, 0xc0001148f0, 0x193, 0xc00010e8a0, 0xc00039e750, 0x13)
        /home/marc/sdk/go1.14.1/src/reflect/value.go:1532 +0xbd
github.com/containous/yaegi/interp.doCompositeSparse.func1(0xc000392000, 0xc000118640)
        /home/marc/go/src/github.com/containous/yaegi/interp/run.go:1773 +0x13d
github.com/containous/yaegi/interp.runCfg(0xc0003a4c00, 0xc000392000)
        /home/marc/go/src/github.com/containous/yaegi/interp/run.go:119 +0x6d
github.com/containous/yaegi/interp.(*Interpreter).run(0xc000102600, 0xc000134100, 0x0)
        /home/marc/go/src/github.com/containous/yaegi/interp/run.go:97 +0x239
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc000102600, 0xc00039a000, 0xc5, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:385 +0x3e8
main.main()
        /home/marc/go/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:94 +0x548
```

**Comment by mvertes** [comment]
This issue is related changes in #543 and #569. Although the parsing is now robust to forward dependencies and recursive structs, the type conversion of functions involving such objects is not always consistent.
