### ISSUE TITLE
forward declaration of an aliased type

### ISSUE THREAD

**Issue by mvertes** [containous/yaegi#592]
The following program `sample.go` triggers a panic:

```go
package main

type T1 T

func foo() T1 {
    return T1(T{"foo"})
}

type T struct {
    Name string
}

func main() {
    println(foo().Name)
}   
```

Expected result:
```console
$ go run ./sample.go
foo
```

Got:
```console
$ yaegi ./sample.go
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc00031c000, 0x40)
        /home/marc/sdk/go1.14.1/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/yaegi/interp.(*Interpreter).Eval.func1(0xc00022de10)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:320 +0xbc
panic(0xcde980, 0x1542e10)
        /home/marc/sdk/go1.14.1/src/runtime/panic.go:967 +0x166
github.com/containous/yaegi/interp.nodeType(0xc00021c180, 0xc000208420, 0x0, 0x0, 0x0, 0x0)
        /home/marc/go/src/github.com/containous/yaegi/interp/type.go:125 +0x3a
github.com/containous/yaegi/interp.nodeType(0xc00021c180, 0xc000208420, 0xc000216e00, 0xc00022d050, 0xc00020c058, 0xc00020a2c0)
        /home/marc/go/src/github.com/containous/yaegi/interp/type.go:398 +0x2a7e
github.com/containous/yaegi/interp.nodeType(0xc00021c180, 0xc000208420, 0xc000216a00, 0xcf49e0, 0xfa7720, 0x0)
        /home/marc/go/src/github.com/containous/yaegi/interp/type.go:379 +0x2683
github.com/containous/yaegi/interp.(*Interpreter).gta.func1(0xc000216700, 0xc00022dbe8)
        /home/marc/go/src/github.com/containous/yaegi/interp/gta.go:108 +0x15a8
github.com/containous/yaegi/interp.(*node).Walk(0xc000216700, 0xc00022dbe8, 0x0)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:184 +0xc9
github.com/containous/yaegi/interp.(*node).Walk(0xc000216100, 0xc00022dbe8, 0x0)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:188 +0x70
github.com/containous/yaegi/interp.(*Interpreter).gta(0xc00021c180, 0xc000216100, 0xc00020e060, 0x4, 0x7ffe65543665, 0x1d, 0x0, 0xc000211500, 0x0, 0x0, ...)
        /home/marc/go/src/github.com/containous/yaegi/interp/gta.go:15 +0x153
github.com/containous/yaegi/interp.(*Interpreter).gtaRetry(0xc00021c180, 0xc00022ddb8, 0x1, 0x1, 0xc00020e060, 0x4, 0x7ffe65543665, 0x1d, 0x0, 0x0)
        /home/marc/go/src/github.com/containous/yaegi/interp/gta.go:228 +0x14a
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc00021c180, 0xc00030e000, 0x86, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:338 +0x194
main.main()
        /home/marc/go/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:94 +0x548

```

**Comment by mvertes** [comment]
The test is ok if `T` is declared prior to `T1`
