### ISSUE TITLE
conversion to time.Duration

### ISSUE THREAD

**Issue by mvertes** [containous/yaegi#597]
The following program `sample.go` triggers a panic:

```go
package main

import (
    "fmt"
    "time"
) 
  
var twentyFourHours = time.Duration(24 * time.Hour)
   
func main() {
    fmt.Println(twentyFourHours.Hours())
}
```

Expected result:
```console
$ go run ./sample.go
24
```

Got:
```console
$ yaegi ./sample.go
reflect: NumOut of non-func type time.Duration
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc00031a000, 0x40)
        /home/marc/sdk/go1.14.1/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/yaegi/interp.(*Interpreter).Eval.func1(0xc00009fe10)
        /home/marc/src/yaegi/interp/interp.go:320 +0xbc
panic(0xc94340, 0xc000072590)
        /home/marc/sdk/go1.14.1/src/runtime/panic.go:967 +0x166
reflect.(*rtype).NumOut(0xd5dba0, 0xc0002f71f0)
        /home/marc/sdk/go1.14.1/src/reflect/type.go:989 +0xe2
github.com/containous/yaegi/interp.nodeType(0xc000001500, 0xc0002f71f0, 0xc000308a00, 0x4, 0xc0002fe3d0, 0x0)
        /home/marc/src/yaegi/interp/type.go:328 +0x1911
github.com/containous/yaegi/interp.(*Interpreter).gta.func1(0xc000308800, 0xc00009fbf0)
        /home/marc/src/yaegi/interp/gta.go:63 +0x7b5
github.com/containous/yaegi/interp.(*node).Walk(0xc000308800, 0xc00009fbf0, 0x0)
        /home/marc/src/yaegi/interp/interp.go:184 +0xc9
github.com/containous/yaegi/interp.(*node).Walk(0xc000308700, 0xc00009fbf0, 0x0)
        /home/marc/src/yaegi/interp/interp.go:188 +0x70
github.com/containous/yaegi/interp.(*node).Walk(0xc000308000, 0xc00009fbf0, 0x0)
        /home/marc/src/yaegi/interp/interp.go:188 +0x70
github.com/containous/yaegi/interp.(*Interpreter).gta(0xc000001500, 0xc000308000, 0xc000034168, 0x4, 0x7ffd8d98764a, 0x17, 0x0, 0xc000096100, 0x0, 0x0, ...)
        /home/marc/src/yaegi/interp/gta.go:15 +0x131
github.com/containous/yaegi/interp.(*Interpreter).gtaRetry(0xc000001500, 0xc00009fdb8, 0x1, 0x1, 0xc000034168, 0x4, 0x7ffd8d98764a, 0x17, 0x0, 0x0)
        /home/marc/src/yaegi/interp/gta.go:231 +0x14a
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc000001500, 0xc000302000, 0xa6, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/marc/src/yaegi/interp/interp.go:338 +0x194
main.main()
        /home/marc/src/yaegi/cmd/yaegi/yaegi.go:94 +0x548

```

Thanks to @nrwiersma for the report.

**Comment by mvertes** [comment]
The test works if `twentyFourHours` is declared inside main
