### ISSUE TITLE
assigning a local var ptr to an interface var fails

### ISSUE THREAD

**Issue by gbernady** [containous/yaegi#609]
The following program `sample.go` triggers a panic:

```go
package main

import (
	"fmt"
	"net"
)

func main() {
	addr := net.TCPAddr{IP: net.IPv4(1,1,1,1), Port: 80}
	var s fmt.Stringer = &addr
	fmt.Println(s.String())
}
```

Expected result:
```console
$ go run ./sample.go
1.1.1.1:80
```

Got:
```console
$ yaegi ./sample.go
run.go:601: ./sample.go:10:23: genInterfaceWrapper error, no method String
./sample.go:9:10: panic
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc000332000, 0x40)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/yaegi/interp.(*Interpreter).Eval.func1(0xc00022fe10)
	/Users/berng/go/src/github.com/containous/yaegi/interp/interp.go:320 +0xbc
panic(0x18deee0, 0x214c1b0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
github.com/containous/yaegi/interp.runCfg.func1(0xc00030a0a0, 0xc000217200)
	/Users/berng/go/src/github.com/containous/yaegi/interp/run.go:113 +0x20c
panic(0x18deee0, 0x214c1b0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
github.com/containous/yaegi/stdlib._fmt_Stringer.String(0x0, 0x0, 0x0)
	/Users/berng/go/src/github.com/containous/yaegi/stdlib/go1_14_fmt.go:111 +0x22
reflect.Value.call(0x18eaf20, 0xc000206890, 0x293, 0x19bc6e7, 0x4, 0x2196618, 0x0, 0x0, 0xc00022fb70, 0x1051b2c, ...)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x18eaf20, 0xc000206890, 0x293, 0x2196618, 0x0, 0x0, 0xc00022fc10, 0x1263cea, 0x18eaf20)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/reflect/value.go:321 +0xb4
github.com/containous/yaegi/interp.callBin.func7(0xc00030a0a0, 0xc00020e600)
	/Users/berng/go/src/github.com/containous/yaegi/interp/run.go:958 +0x1a2
github.com/containous/yaegi/interp.runCfg(0xc000217200, 0xc00030a0a0)
	/Users/berng/go/src/github.com/containous/yaegi/interp/run.go:119 +0x6d
github.com/containous/yaegi/interp.(*Interpreter).run(0xc00021c180, 0xc000216900, 0xc00030a000)
	/Users/berng/go/src/github.com/containous/yaegi/interp/run.go:97 +0x239
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc00021c180, 0xc000312000, 0xa3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/berng/go/src/github.com/containous/yaegi/interp/interp.go:388 +0x41f
main.main()
	/Users/berng/go/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:94 +0x548```

**Comment by gbernady** [comment]
On the other hand, this works:

```go
package main

import (
	"fmt"
	"net/url"
)

func main() {
	u, _ := url.Parse("http://example.com")
	var s fmt.Stringer = u
	println(s.String())
}
```

Expected result:
```console
$ go run ./sample.go
http://example.com
```

Got:
```console
$ yaegi ./sample.go
http://example.com
```

In both cases the `String()` method is defined on a pointer receiver.
