### ISSUE TITLE
panic calling a function from an array of functions.

### ISSUE THREAD

**Issue by james-lawrence** [containous/yaegi#642]
The following program `sample.go` triggers a panic:

```go
package main

func main() {
	var options = []func(){bar}
	choice := options[0]
	choice()
}

func bar() {}
```

Expected result:
```console
$ go run ./example.go
```

Got:
```console
$ yaegi example.go 
example.go:4:16: panic
panic: reflect.Set: value of type *interp.node is not assignable to type func() [recovered]
	panic: reflect.Set: value of type *interp.node is not assignable to type func()

goroutine 1 [running]:
github.com/containous/yaegi/interp.runCfg.func1(0xc00016a2d0, 0xc00016cd00)
	/shared/james-lawrence/go/src/github.com/containous/yaegi/interp/run.go:107 +0x1e0
panic(0xc957a0, 0xc000152640)
	/usr/lib/go/src/runtime/panic.go:679 +0x1b2
reflect.Value.assignTo(0xd59e40, 0xc00016da00, 0x16, 0xdd3392, 0xb, 0xc8c5a0, 0x0, 0x203000, 0x14e90c0, 0xc0001a9c28)
	/usr/lib/go/src/reflect/value.go:2403 +0x432
reflect.Value.Set(0xc8c5a0, 0xc000154160, 0x193, 0xd59e40, 0xc00016da00, 0x16)
	/usr/lib/go/src/reflect/value.go:1537 +0xbd
github.com/containous/yaegi/interp.arrayLit.func1(0xc00016a2d0, 0xd59e40)
	/shared/james-lawrence/go/src/github.com/containous/yaegi/interp/run.go:1362 +0x100
github.com/containous/yaegi/interp.runCfg(0xc00016cd00, 0xc00016a2d0)
	/shared/james-lawrence/go/src/github.com/containous/yaegi/interp/run.go:112 +0x7a
github.com/containous/yaegi/interp.(*Interpreter).run(0xc000256000, 0xc00016c300, 0xc00016a0a0)
	/shared/james-lawrence/go/src/github.com/containous/yaegi/interp/run.go:93 +0x12c
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc000256000, 0xc000260000, 0x6a, 0x26a, 0xc000260000, 0x6a, 0x0, 0x1)
	/shared/james-lawrence/go/src/github.com/containous/yaegi/interp/interp.go:303 +0x3f0
main.main()
	/shared/james-lawrence/go/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:82 +0x42d

```

**Comment by james-lawrence** [comment]
will check

**Comment by james-lawrence** [comment]
```
package main

import (
	"rand"
	"log"
)

func main() {
	var options = []func(){bar, foo}
	choice := options[0]
	choice()
}

func bar() {
	log.Println("bar")
}
func foo() {
}
```
minor adjustment (this is on 8.6.x)

**Comment by mvertes** [comment]
Ok, bug confirmed, thanks.
