### ISSUE TITLE
equality test involving interface

### ISSUE THREAD

**Issue by mvertes** [containous/yaegi#685]
The following program `sample.go` triggers a panic:

```go
package main
  
type T int

func (t T) Error() string { return "T: error" }

var invalidT T

func main() {
    var err error
    if err != invalidT {
        println("ok")
    }
}
```

Expected result:
```console
$ go run ./sample.go
ok
```

Got:
```console
$ yaegi ./sample.go
./sample.go:10:6: panic
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc000164400, 0x40)
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/yaegi/interp.(*Interpreter).Eval.func1(0xc000293df0)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:320 +0xbc
panic(0xce3960, 0x1549e70)
        /usr/lib/go/src/runtime/panic.go:969 +0x166
github.com/containous/yaegi/interp.runCfg.func1(0xc00014f680, 0xc00039a400)
        /home/marc/go/src/github.com/containous/yaegi/interp/run.go:113 +0x20c
panic(0xce3960, 0x1549e70)
        /usr/lib/go/src/runtime/panic.go:969 +0x166
github.com/containous/yaegi/interp.notEqual.func23(0xc00014f680, 0xc00035ee40)
        /home/marc/go/src/github.com/containous/yaegi/interp/op.go:3770 +0x52
github.com/containous/yaegi/interp.runCfg(0xc00039a400, 0xc00014f680)
        /home/marc/go/src/github.com/containous/yaegi/interp/run.go:119 +0x6d
github.com/containous/yaegi/interp.(*Interpreter).run(0xc000102c00, 0xc00015bc00, 0xc00014f5e0)
        /home/marc/go/src/github.com/containous/yaegi/interp/run.go:97 +0x239
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc000102c00, 0xc000398000, 0xb5, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:388 +0x41f
main.main()
        /home/marc/go/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:138 +0x553

```

**Comment by nrwiersma** [comment]
@mvertes I cannot reproduce on master.

**Comment by mvertes** [comment]
Still fails with the same error on my linux laptop.
