### ISSUE TITLE
use of arrays in recursive types

### ISSUE THREAD

**Issue by mvertes** [containous/yaegi#687]
The following program `sample.go` triggers a panic:

```go
package main
  
import "fmt"

type Node struct {
    Name  string
    Child []Node
}

func main() {
    a := Node{Name: "hello"}
    a.Child = append(a.Child, Node{Name: "world"})
    fmt.Println(a)
    a.Child[0].Child = append([]Node{}, Node{Name: "sunshine"})
    fmt.Println(a)
}
```

Expected result:
```console
$ go run ./sample.go
{hello [{world []}]}
{hello [{world [{sunshine []}]}]}
```

Got:
```console
$ yaegi ./sample.go
{hello [{world []}]}
/home/marc/yt/rs3.go:11:12: panic
reflect: call of reflect.Value.Field on interface Value
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc00032e000, 0x40)
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/yaegi/interp.(*Interpreter).Eval.func1(0xc00021ddf0)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:330 +0xbc
panic(0xcd3c60, 0xc00020af20)
        /usr/lib/go/src/runtime/panic.go:969 +0x166
github.com/containous/yaegi/interp.runCfg.func1(0xc0003020a0, 0xc000221c00)
        /home/marc/go/src/github.com/containous/yaegi/interp/run.go:114 +0x20c
panic(0xcd3c60, 0xc00020af20)
        /usr/lib/go/src/runtime/panic.go:969 +0x166
reflect.Value.Field(0xcc9e40, 0xc000204c40, 0x194, 0x1, 0xc8fb80, 0xc0002f6910, 0x197)
        /usr/lib/go/src/reflect/value.go:827 +0x123
reflect.Value.FieldByIndex(0xcc9e40, 0xc000204c40, 0x194, 0xc0002022e8, 0x1, 0x1, 0xcc9e40, 0xc000204c40, 0x194)
        /usr/lib/go/src/reflect/value.go:859 +0x2c2
github.com/containous/yaegi/interp.getIndexSeq.func2(0xc0003020a0, 0xc00020e8c0)
        /home/marc/go/src/github.com/containous/yaegi/interp/run.go:1407 +0x8f
github.com/containous/yaegi/interp.runCfg(0xc000221c00, 0xc0003020a0)
        /home/marc/go/src/github.com/containous/yaegi/interp/run.go:120 +0x6d
github.com/containous/yaegi/interp.(*Interpreter).run(0xc0002361a0, 0xc000221200, 0xc000302000)
        /home/marc/go/src/github.com/containous/yaegi/interp/run.go:98 +0x239
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc0002361a0, 0xc00030a000, 0x105, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:406 +0x52b
main.main()
        /home/marc/go/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:143 +0x553
```

**Comment by nrwiersma** [comment]
Due to the fact that the `[]Node` will end up being a `[]interface{}` (recursion), when derefing the `interface{}` the `reflect.Value` becomes unsettable, and I see no way around this. I think the only viable solution is to make recursive interface values `valueInterface` wrappers. This is the only way I see to make the case of `[]Node` possible.

**Comment by nrwiersma** [comment]
That idea is no good, it will interact too much with bin functions. The only way I have found to do it is with `unsafe`.
