### ISSUE TITLE
Can't assign a returned chan from a bin call to a read only chan

### ISSUE THREAD

**Issue by jlevesy** [containous/yaegi#701]
The following program `sample.go` triggers a panic:

```go
package main

import (
	"time"
)

func main() {
	var tick <-chan time.Time = time.Tick(time.Millisecond)
	_ = tick
       println("success")
}

// Output:
// success

```

Expected result:
```console
$ go run ./sample.go
success
```

Got:
```console
$ yaegi ./sample.go
0xc0001114a0
case14/main.go:8:30: panic
reflect.Set: value of type <-chan time.Time is not assignable to type chan time.Time
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc000152400, 0x40)
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/yaegi/interp.(*Interpreter).Eval.func1(0xc0000c3df0)
	/home/jlevesy/code/src/github.com/containous/yaegi/interp/interp.go:330 +0xbc
panic(0xc9b420, 0xc0001ac790)
	/usr/lib/go/src/runtime/panic.go:969 +0x166
github.com/containous/yaegi/interp.runCfg.func1(0xc0001397c0, 0xc000145700)
	/home/jlevesy/code/src/github.com/containous/yaegi/interp/run.go:114 +0x20c
panic(0xc9b420, 0xc0001ac790)
	/usr/lib/go/src/runtime/panic.go:969 +0x166
reflect.Value.assignTo(0xc94de0, 0xc0001ac788, 0x92, 0xdce02f, 0xb, 0xc955a0, 0x0, 0xc000111520, 0x1, 0x1)
	/usr/lib/go/src/reflect/value.go:2403 +0x426
reflect.Value.Set(0xc955a0, 0xc00011c720, 0x192, 0xc94de0, 0xc0001ac788, 0x92)
	/usr/lib/go/src/reflect/value.go:1532 +0xbd
github.com/containous/yaegi/interp.callBin.func8(0xc0001397c0, 0xc00011e8a0)
	/home/jlevesy/code/src/github.com/containous/yaegi/interp/run.go:1047 +0x2df
github.com/containous/yaegi/interp.runCfg(0xc000145700, 0xc0001397c0)
	/home/jlevesy/code/src/github.com/containous/yaegi/interp/run.go:120 +0x6d
github.com/containous/yaegi/interp.(*Interpreter).run(0xc0001b61a0, 0xc000144800, 0xc000139720)
	/home/jlevesy/code/src/github.com/containous/yaegi/interp/run.go:98 +0x239
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc0001b61a0, 0xc00030a000, 0xa1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/jlevesy/code/src/github.com/containous/yaegi/interp/interp.go:406 +0x52b
main.main()
	/home/jlevesy/code/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:143 +0x553
```

**Comment by jlevesy** [comment]
It has to be noted that this only happens on a binary call, the following sample works properly:

```
(31 ms) yaegi ⍉ λ cat case14/main.go 
package main

import "time"

func ch() <-chan time.Time { return nil }

func main() {
	var tick <-chan time.Time = ch()
	_ = tick

	println("success")
}

// Output:
// success
(8 ms) yaegi λ yaegi case14/main.go
success
```
